// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlEraVP4tDe0thdWL7SQWkRJezJ0jcYGg',
    appId: '1:652086803695:web:8489ee94938a687363ef1a',
    messagingSenderId: '652086803695',
    projectId: 'plantist-9f454',
    authDomain: 'plantist-9f454.firebaseapp.com',
    storageBucket: 'plantist-9f454.appspot.com',
    measurementId: 'G-B7VYJ2MBGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6b4qa3UThTffjobuzxRIFvYcz-mHjFK4',
    appId: '1:652086803695:android:6178e5690613536c63ef1a',
    messagingSenderId: '652086803695',
    projectId: 'plantist-9f454',
    storageBucket: 'plantist-9f454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrwRbvbFV8KqsVQ_uZijb2PnxfXP_zMA',
    appId: '1:652086803695:ios:93bb9c3a300a23f863ef1a',
    messagingSenderId: '652086803695',
    projectId: 'plantist-9f454',
    storageBucket: 'plantist-9f454.appspot.com',
    iosBundleId: 'com.example.plantist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrwRbvbFV8KqsVQ_uZijb2PnxfXP_zMA',
    appId: '1:652086803695:ios:93bb9c3a300a23f863ef1a',
    messagingSenderId: '652086803695',
    projectId: 'plantist-9f454',
    storageBucket: 'plantist-9f454.appspot.com',
    iosBundleId: 'com.example.plantist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlEraVP4tDe0thdWL7SQWkRJezJ0jcYGg',
    appId: '1:652086803695:web:767eb17c8c1a045f63ef1a',
    messagingSenderId: '652086803695',
    projectId: 'plantist-9f454',
    authDomain: 'plantist-9f454.firebaseapp.com',
    storageBucket: 'plantist-9f454.appspot.com',
    measurementId: 'G-DGKB6YH9R8',
  );
}
